### ISSUE TITLE
Summoning Guns

### ISSUE THREAD

**Issue by GilgusMaximus** [Bussler/LudumDare55#17]

**Comment by GilgusMaximus** [comment]
- Try to get a circle as close to the circle the player walked around the item
- And calculate from that the hitbox

**Comment by GilgusMaximus** [comment]
Full implementation depends on #13

**Comment by Neroware** [comment]
Implement using Unity splines. Node coordinates can be used to fit a circle. Collision would be a basic sphere.
I only see issues regarding fitting art along the spline path. That is also a thing for our artists.

**Comment by Neroware** [comment]
1. Step: Implement circle detection
2. Step: Incorporate movement and dynamic spline generation
