### ISSUE TITLE
Let enemies increase player highscore

### ISSUE THREAD

**Issue by Bussler** [Bussler/LudumDare55#57]
- Give an enemy some highscore
- Let the enemy increase the highscore on death

The following things should affect the highscore:
- Enemies killed
- Summons performed
- Speed

**Comment by Neroware** [comment]
I will also add a time score which counts down. Very sweet for the speedrunning community ;)

**Comment by Neroware** [comment]
Done except for points given for completed ritual circles.

**Comment by Bussler** [comment]
closed by  #85
